image: node:10-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

# Jobs
install_dependencies:
  stage: build
  only:
    - tags
  script:
    - yarn install

publish_package:
  stage: deploy
  only:
    - tags
  script:
    - npm config set registry https://registry.npmjs.org/
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm whoami
    - yarn build
    - npm publish --verbose
  artifacts:
    paths:
      - dist/
