image: node:10-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

# Jobs
install_dependencies:
  stage: build
  script:
    - yarn install

publish_package:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish
  artifacts:
    paths:
      - dist/
